Desafio/Models/Endereco.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desafio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereco
    {
        public int enderecoId { get; set; }
        public string estado { get; set; }
        public string cidade { get; set; }
        public string bairro { get; set; }
        public string endereco1 { get; set; }
        public Nullable<int> numero { get; set; }
        public string complemento { get; set; }
        public int pessoaId { get; set; }
        public string cep { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}

Desafio/Models/Pessoa.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desafio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pessoa()
        {
            this.Endereco = new HashSet<Endereco>();
            this.Numero = new HashSet<Numero>();
            this.Numero1 = new HashSet<Numero>();
        }
    
        public int pessoaId { get; set; }
        public string nome { get; set; }
        public System.DateTime dataNascimento { get; set; }
        public string cpf { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Endereco> Endereco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Numero> Numero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Numero> Numero1 { get; set; }
    }
}

Desafio/Controllers/PessoaController.cs
using Desafio.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Desafio.Controllers
{
    public class PessoaController : Controller
    {
        IATecEntities db = new IATecEntities();

        [HttpGet]
        public ActionResult Listar()
        {
            var lista = db.Pessoa.ToList();

            return View(lista);
        }

        [HttpGet]
        public ActionResult Criar()
        {
            return PartialView("_Criar");
        }

        [HttpPost]
        public ActionResult Criar(Pessoa pessoa)
        {
            db.Pessoa.Add(pessoa);
            db.SaveChanges();

            return RedirectToAction("Listar");
        }

        [HttpGet]
        public ActionResult Editar(int pessoaId)
        {
            var pessoa = db.Pessoa.FirstOrDefault(x => x.pessoaId == pessoaId);
            ViewBag.data = pessoa.dataNascimento.ToString("yyyy-MM-dd");
            ViewBag.pessoaId = pessoaId;
            ViewBag.cpf = pessoa.cpf;

            return View(pessoa);
        }
        [HttpPost]
        public ActionResult Editar(Pessoa pessoa)
        {
            ViewBag.pessoaId = pessoa.pessoaId;
            var p = db.Pessoa.FirstOrDefault(x => x.pessoaId == pessoa.pessoaId);

            p.nome = pessoa.nome;
            p.cpf = pessoa.cpf;
            p.dataNascimento = pessoa.dataNascimento;
            p.email = pessoa.email;

            db.Entry(p).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Listar");
        }
        [HttpGet]
        public ActionResult Detalhes(int pessoaId)
        {
            var pessoa = db.Pessoa.FirstOrDefault(x => x.pessoaId == pessoaId);
            ViewBag.numero = db.Numero.Where(x => x.pessoaId == pessoaId).ToList();
            ViewBag.endereco = db.Endereco.Where(x => x.pessoaId == pessoaId).ToList();
            return View(pessoa);
        }
        [HttpPost]
        public ActionResult Deletar(int pessoaId)
        {
            var listaT = db.Numero.Where(x => x.pessoaId == pessoaId).ToList();
            foreach (var n in listaT)
            {
                db.Numero.Remove(n);
            }
            var listaE = db.Endereco.Where(x => x.pessoaId == pessoaId).ToList();
            foreach (var e in listaE)
            {
                db.Endereco.Remove(e);
            }
            var pessoa = db.Pessoa.FirstOrDefault(x => x.pessoaId == pessoaId);
            db.Pessoa.Remove(pessoa);
            db.SaveChanges();
            return RedirectToAction("Listar");
        }
        //TELEFONE
        [HttpGet]
        public ActionResult _ListarNumero(int pessoaId)
        {
            var lista = db.Numero.Where(x => x.pessoaId == pessoaId).ToList();
            return PartialView(lista);
        }
        [HttpGet]
        public ActionResult Telefone(int pessoaId)
        {
            ViewBag.pessoaId = pessoaId;
            return View();
        }

        [HttpPost]
        public ActionResult Telefone(Numero numero)
        {
            ViewBag.pessoaId = numero.pessoaId;
            db.Numero.Add(numero);
            db.SaveChanges();

            return RedirectToAction("Telefone", new { pessoaId = numero.pessoaId });
        }
        [HttpGet]
        public ActionResult DeletarNumero(int numeroId)
        {
            var numero = db.Numero.FirstOrDefault(x => x.numeroId == numeroId);
            ViewBag.pessoaId = numero.pessoaId;
            db.Numero.Remove(numero);
            db.SaveChanges();

            return RedirectToAction("Telefone", new { pessoaId = numero.pessoaId });
        }

        //ENDEREÇO
        [HttpGet]
        public ActionResult _ListarEndereco(int pessoaId)
        {
            var lista = db.Endereco.Where(x => x.pessoaId == pessoaId).ToList();
            return PartialView(lista);
        }
        [HttpGet]
        public ActionResult Endereco(int pessoaId)
        {
            ViewBag.pessoaId = pessoaId;
            return View();
        }
        [HttpPost]
        public ActionResult Endereco(Endereco endereco)
        {
            ViewBag.pessoaId = endereco.pessoaId;
            db.Endereco.Add(endereco);
            db.SaveChanges();

            return RedirectToAction("Endereco", new { pessoaId = endereco.pessoaId });
        }
        [HttpGet]
        public ActionResult DeletarEndereco(int enderecoId)
        {
            var endereco = db.Endereco.FirstOrDefault(x => x.enderecoId == enderecoId);
            ViewBag.pessoaId = endereco.pessoaId;
            db.Endereco.Remove(endereco);
            db.SaveChanges();

            return RedirectToAction("Endereco", new { pessoaId = endereco.pessoaId });
        }

    }
}

Desafio/Views/Pessoa/Detalhes.cshtml
@model Desafio.Models.Pessoa

@{
    ViewBag.Title = "Detalhes";

    var endereco = ViewBag.endereco;
}

<div class="card">
    <div class="card-header">
        <span style="font-size: 15pt">
            Detalhes <a class="btn btn-outline-dark pull-right" href="@Url.Action("Editar", new { Model.pessoaId })"><i class="fa fa-pencil" aria-hidden="true"></i></a>
        </span>
    </div>
    <div class="card-body">

        <div class="row">
            <div class="col-md-4">


                <dl class="dl-horizontal">
                    <dt>
                        Nome
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.nome)
                    </dd>

                    <dt>
                        Data de Nascimento
                    </dt>

                    <dd>
                        @Model.dataNascimento.ToString("dd/MM/yyyy")
                    </dd>

                    <dt>
                        CPF
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.cpf)
                    </dd>

                    <dt>
                        Email
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.email)
                    </dd>

                </dl>
            </div>
            <div class="col-md-4">
                <h4>Endereço(s)</h4>
                <div class="card" style="width: 18rem;">
                    <ul class="list-group list-group-flush">
                        @foreach (var item in Model.Endereco)
                        {
                            <li class="list-group-item" style="font-size:10pt">
                                @item.endereco1, @item.numero<br />
                                @item.complemento<br />
                                @item.bairro<br />
                                @item.cidade - @item.estado  <br />
                                @item.cep
                            </li>
                        }
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <h4>Telefone(s)</h4>
                <div class="card" style="width: 18rem;">
                    <ul class="list-group list-group-flush">
                        @foreach (var item in Model.Numero)
                        {

                            <li class="list-group-item">
                                @item.numero1
                            </li>
                        }
                    </ul>
                </div>
            </div>

        </div>
        <a class="btn btn-outline-dark pull-right" href="@Url.Action("Listar")"><i class="fa fa-backward" aria-hidden="true"> Voltar</i></a>
    </div>
</div>

Desafio/Views/Pessoa/Editar.cshtml
@model Desafio.Models.Pessoa

@{
    ViewBag.Title = "Editar";
        var pessoaId = ViewBag.pessoaId;
}


<div class="card ">
    <div class="card-header">
        <span style="font-size: 15pt">Editar Pessoa </span><a class="btn btn-outline-dark pull-right" href="@Url.Action("Listar")"><i class="fa fa-backward" aria-hidden="true"></i> Voltar </a>
    </div>
    <div class="card-body">
        <a class="btn btn-warning" href="@Url.Action("Editar", new { pessoaId })">Dados</a>  <a class="btn btn-outline-primary" href="@Url.Action("Endereco", new { pessoaId })">Endereço</a>  <a class="btn btn-outline-success" href="@Url.Action("Telefone", new { pessoaId })">Telefone</a>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.pessoaId)

                <div class="form-group">
                    @Html.Label("Nome ", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Data de Nascimento", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @*@Html.EditorFor(model => model.dataNascimento.Date, new { htmlAttributes = new { @class = "form-control" } })*@
                        <input class="form-control" type="date" name="dataNascimento"  value="@ViewBag.data"/>
                        @Html.ValidationMessageFor(model => model.dataNascimento, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("CPF ", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input class="form-control mask-cpf" type="text" name="cpf" data-mask="999.999.999-99" value="@ViewBag.cpf"/>
                        @Html.ValidationMessageFor(model => model.cpf, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Email ", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" ,required="required"} })
                        @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Salvar" class="btn btn-success" />
                        <a href="@Url.Action("Listar", "Pessoa")" class="btn btn-danger"> Cancelar</a>
                    </div>
                </div>

            </div>
        }

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }
    </div>
</div>

Desafio/Views/Pessoa/Endereco.cshtml
@model Desafio.Models.Endereco

@{
    ViewBag.Title = "_Endereco";
    var pessoaId = ViewBag.pessoaId;
}

<div class="card">
    <div class="card-header">
        <span style="font-size: 15pt">Editar Pessoa<a class="btn btn-outline-dark pull-right" href="@Url.Action("Listar")"><i class="fa fa-backward" aria-hidden="true"></i> Voltar </a></span>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <a class="btn btn-outline-warning" href="@Url.Action("Editar", new { pessoaId })">Dados</a>  <a class="btn btn-primary" href="@Url.Action("Endereco", new { pessoaId })">Endereço</a>  <a class="btn btn-outline-success" href="@Url.Action("Telefone", new { pessoaId })">Telefone</a>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.enderecoId)

                        <div class="form-group">
                            @Html.Label("CEP ", htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.cep, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.cep, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Estado ", htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.estado, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Cidade ", htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.cidade, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.cidade, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Bairro ", htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.bairro, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.bairro, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Rua", htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.endereco1, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.endereco1, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Número ", htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.numero, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.numero, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Complemento", htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.complemento, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.complemento, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <d2iv class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Salvar" class="btn btn-success" />
                            </div>
                        </d2iv>
                    </div>

                }
            </div>

            <div class="col-md-6">
                @{Html.RenderAction("_ListarEndereco", "Pessoa", new { pessoaId = pessoaId });}

            </div>
            @Scripts.Render("~/bundles/jqueryval")

        </div>
    </div>

Desafio/Views/Pessoa/Listar.cshtml
@model IEnumerable<Desafio.Models.Pessoa>

@{
    ViewBag.Title = "Listar";

}


<div class="card">
    <div class="card-header">
        <span style="font-size: 15pt">Lista de Pessoas</span> <a href="@Url.Action("Criar")" class="btn btn-outline-primary pull-right" data-toggle="modal" data-target=".bd-example-modal-sm">Nova Pessoa</a>
    </div>
    <div class="card-body">
        <table id="table" class="table table-responsive-sm" style="width:100%">
            <tr>
                <th>
                    Nome
                </th>
                <th>
                    Data de Nascimento
                </th>
                <th>
                    CPF
                </th>
                <th>
                    Email
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.nome)
                    </td>
                    <td>
                        @item.dataNascimento.ToString("dd/MM/yyyy")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.cpf)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.email)
                    </td>
                    <td>
                        <a class="btn btn-outline-dark" href="@Url.Action("Editar", new { item.pessoaId })"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                        <a class="btn btn-outline-dark" href="@Url.Action("Detalhes", new { item.pessoaId })"><i class="fa fa-list" S aria-hidden="true"></i></a>
                        @*<a href="@Url.Action("Deletar", new { item.pessoaId })"><i class="fa fa-remove" aria-hidden="true"></i></a>*@
                        <button class="btn btn-outline-dark" title="Remover" data-toggle="modal" data-target="#Modal" id="remo" onclick="myFunction('@item.pessoaId')"><i class="fa fa-remove" aria-hidden="true"></i></button>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

@*MODAL DE EXCLUSÃO DE PESSOA*@
<div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        @using (Html.BeginForm("Deletar", "Pessoa", FormMethod.Post))
        {
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Remover</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    Deseja realmente remover?

                    <input type="hidden" id="pessoaId" name="pessoaId" value="" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <input type="submit" value="Remover" class="btn btn-danger">
                </div>
            </div>
        }
    </div>
</div>

@*MODAL DE INCLUSÃO DE PESSOA*@
<div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            @{Html.RenderAction("Criar", "Pessoa");}
        </div>
    </div>
</div>

<script>
    function myFunction(id) {
        $("#pessoaId").val(id);
    }
</script>   

Desafio/Views/Pessoa/Telefone.cshtml
@model Desafio.Models.Numero

@{
    ViewBag.Title = "_Telefone";
    var pessoaId = ViewBag.pessoaId;
}

<div class="card">
    <div class="card-header">
        <span style="font-size: 15pt">Editar Pessoa<a class="btn btn-outline-dark pull-right" href="@Url.Action("Listar")"><i class="fa fa-backward" aria-hidden="true"></i> Voltar </a></span>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <a class="btn btn-outline-warning" href="@Url.Action("Editar", new { pessoaId })">Dados</a>  <a class="btn btn-outline-primary" href="@Url.Action("Endereco", new { pessoaId })">Endereço</a>  <a class="btn btn-success" href="@Url.Action("Telefone", new { pessoaId })">Telefone</a>

                @using (Html.BeginForm())
{
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(x => x.pessoaId);

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.numeroId)

                        <div class="form-group">
                            @Html.Label("Número", htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-10">
                                <input class="form-control mask-numero" type="text" name="numero1" data-mask="(00) 0 0000-0000" />
                                @Html.ValidationMessageFor(model => model.numero1, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Salvar" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
}
            </div>
            <div class="col-md-6">
                @{Html.RenderAction("_ListarNumero","Pessoa",new { pessoaId = pessoaId });}
                
            </div>

        </div>
        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }
    </div>
</div>

Desafio/Views/Pessoa/_Criar.cshtml
@model Desafio.Models.Pessoa
@{
    ViewBag.Title = "Criar";
    Layout = null;
}
<h2 style="margin: 10px">Nova Pessoa</h2>

@using (Html.BeginForm("Criar", "Pessoa", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Nome ", htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Data de Nascimento", htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dataNascimento, new { htmlAttributes = new { @class = "form-control", type = "date", required = "required" } })
                @Html.ValidationMessageFor(model => model.dataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("CPF ", htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-10">
                <input class="form-control mask-cpf" type="text" name="cpf" data-mask="999.999.999-99" data-val="true" required="required" />

                @Html.ValidationMessageFor(model => model.cpf, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Email ", htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}
<script>
        $(".mask-cpf").each(function () {
            $(this).mask($(this).attr("data-mask"));
        });
</script>

Desafio/Views/Pessoa/_ListarEndereco.cshtml
@model IEnumerable<Desafio.Models.Endereco>

@{
    ViewBag.Title = "_ListarEndereco";
    Layout = null;
}

<div class="card" style="width: 18rem;">
    <ul class="list-group list-group-flush">
        @foreach (var item in Model)
        {

        <li class="list-group-item" style="font-size:10pt">
            @Html.DisplayFor(modelItem => item.endereco1), @Html.DisplayFor(modelItem => item.numero)<a class="pull-right btn btn-sm btn-danger" href="@Url.Action("DeletarEndereco","Pessoa", new { item.enderecoId })"><i class="fa fa-remove" aria-hidden="true"></i></a><br />
            @Html.DisplayFor(modelItem => item.complemento)<br />
            @Html.DisplayFor(modelItem => item.bairro)<br />
            @Html.DisplayFor(modelItem => item.cidade) - @Html.DisplayFor(modelItem => item.estado)  <br />
            @Html.DisplayFor(modelItem => item.cep)

        </li>
        }
    </ul>
</div>

Desafio/Views/Pessoa/_ListarNumero.cshtml
@model IEnumerable<Desafio.Models.Numero>

@{
    ViewBag.Title = "ListarNumero";
    Layout = null;
}


<div class="card" style="width: 18rem;">
    <ul class="list-group list-group-flush">
        @foreach (var item in Model)
        {

        <li class="list-group-item">
            @Html.DisplayFor(modelItem => item.numero1)
            <a class="pull-right btn btn-sm btn-danger" href="@Url.Action("DeletarNumero","Pessoa", new { item.numeroId })"><i class="fa fa-remove" aria-hidden="true"></i></a>
        </li>
        }
    </ul>
</div>